services:
  - type: web
    name: money-planner
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: file:./dev.db
      - key: DEMO_MODE
        value: "true"
